# Generated by Django 5.2b1 on 2025-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
